# own bins
export PATH="~/bin:${PATH}"

# history prefs
export HISTSIZE=50000
export HISTCONTROL="erasedups:ignoredups:ignorespace"
export HISTIGNORE="bg:fg:rm *:exit"

# no expansion of cd ~
complete -r cd

# editor
export EDITOR=vim

# pager options
export LESS="$LESS -i -F -R -X"

# pager syntax highlighting if available
if which "src-hilite-lesspipe.sh" >/dev/null; then
    export LESSOPEN="| src-hilite-lesspipe.sh %s"
fi

# sources local profile
[[ -r ~/.bash_profile_local ]] && . ~/.bash_profile_local

# sources bashrc for interactive login shells
[[ -f ~/.bashrc ]] && [[ $- == *i* ]] && shopt login_shell >/dev/null && . ~/.bashrc
