# own bins
export PATH="${HOME}/bin:${PATH}"

# history prefs
export HISTSIZE=50000
export HISTCONTROL="erasedups:ignoredups:ignorespace"
export HISTIGNORE="bg:fg:rm *:exit"

# editor
export EDITOR=vim

# pager options
export LESS="$LESS -i -F -R -X"

# pager syntax highlighting if available
if type src-hilite-lesspipe.sh >/dev/null 2>/dev/null; then
    export LESSOPEN="| src-hilite-lesspipe.sh %s"
elif [[ -f /usr/share/source-highlight/src-hilite-lesspipe.sh ]]; then
    export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
fi


# sources local profile
[[ -r ~/.bash_profile_local ]] && . ~/.bash_profile_local

# sources bashrc for interactive login shells
[[ -f ~/.bashrc ]] && [[ $- == *i* ]] && shopt login_shell >/dev/null && . ~/.bashrc
