export _bin_prefixes=( "" /usr/local /opt/local /opt )

# if not running bash 4, tries to find one and launches it with the same options
if [[ $BASH_VERSINFO != "4" ]]; then
    for bin_prefix in "${_bin_prefixes[@]}"; do
        if [[ -x ${bin_prefix}/bin/bash && $(${bin_prefix}/bin/bash -c 'echo $BASH_VERSINFO') = "4" ]]; then
            # launches bash with same options as current bash, but respects
            # whether it's a login shell
            if shopt -q login_shell; then
                exec ${bin_prefix}/bin/bash -$- -l
            else
                exec ${bin_prefix}/bin/bash -$-
            fi
        fi
   done
fi

# own bins
export PATH="${HOME}/bin:${PATH}"

# history prefs
export HISTSIZE=50000
export HISTCONTROL="erasedups:ignoredups:ignorespace"
export HISTIGNORE="bg:fg:rm *:exit"

# no expansion of cd ~
complete -r cd

# editor
export EDITOR=vim

# pager options
export LESS="$LESS -i -F -R -X"

# pager syntax highlighting if available
if which "src-hilite-lesspipe.sh" >/dev/null 2>/dev/null; then
    export LESSOPEN="| src-hilite-lesspipe.sh %s"
fi

# sources local profile
[[ -r ~/.bash_profile_local ]] && . ~/.bash_profile_local

# sources bashrc for interactive login shells
[[ -f ~/.bashrc ]] && [[ $- == *i* ]] && shopt login_shell >/dev/null && . ~/.bashrc
